# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - dashboards
  - deploy.yml
  - rbac.yml

images:
  - name: grafana/grafana
    newName: registry.sighup.io/fury/grafana/grafana
    newTag: 8.1.2
  - name: kiwigrid/k8s-sidecar
    newName: registry.sighup.io/fury/kiwigrid/k8s-sidecar
    newTag: 1.12.3

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards.yaml

secretGenerator:
  - name: grafana-datasources
    files:
      - prometheus.yaml=prometheus.yaml
