# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - thanos-compact.yaml
  - servicemonitor.yml

images:
  - name: thanos
    newName: reg.sighup.io/sighupio/fury/thanos
    newTag: v0.12.2
