# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

bases:
  - vendor/katalog/monitoring/prometheus-operated
  - vendor/katalog/monitoring/prometheus-operator

resources:
  - add-alert.yml
