# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  name: thanos-query
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: thanos-query.rules
      rules:
        - alert: ThanosQueryIsNotRunning
          expr: up{job="thanos-query-http"} == 0 or absent({job="thanos-query-http"})
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Thanos Query is not running
        - alert: ThanosQueryGrpcErrorRate
          expr: rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable",job="thanos-query-http"}[5m]) > 0
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: Thanos Query is returning Internal/Unavailable errors
            description: Grafana is not showing metrics
